M48
; DRILL file {KiCad (6.99.0-1031-g46d719ed42)} date Thursday, March 31, 2022 at 12:05:21 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-31T00:05:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-1031-g46d719ed42)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X0.75Y-0.75
X0.75Y-6.6
X7.55Y-0.75
X7.55Y-6.6
T0
M30
