# Project information
site_name: OpenSmartMeter by EnAccess
site_url: https://enaccess.github.io/OpenSmartMeter/
site_description: >-
  This is the documentation for the OpenSmartMeter by EnAccess

# Repository
repo_name: EnAccess/OpenSmartMeter
repo_url: https://github.com/EnAccess/OpenSmartMeter
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # schema: enaccess
    primary: custom
    accent: custom
  logo: assets/EnAccess_Logo_Digital_Inverse.svg
  features:
    - content.action.edit
    - content.action.view
    # Disabled to prevent automatic inlining
    # - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # I find this has a weird look and feel, but can be enabled.
    # - toc.integrate

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EnAccess
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/enaccessfdn

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EnAccess
      repo: OpenSmartMeter
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde

# Extra stuff
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Firmware Documentation:
    - Firmware Design: firmware/design.md
    - Calibration: firmware/calibration.md
    - Accuracy Test and Compliance Report: firmware/accuracy_and_compliance_report.md
  - Hardware Documentation: hardware/index.md
  - Web Software and API documentation: backend/api-documentation.md
  - Example: example.md
  - Readme: README.md
