# Project information
site_name: OpenSmartMeter by EnAccess
site_url: https://enaccess.github.io/OpenSmartMeter/
site_description: >-
  This is the documentation for the OpenSmartMeter by EnAccess

# Repository
repo_name: EnAccess/OpenSmartMeter
repo_url: https://github.com/EnAccess/OpenSmartMeter
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: light blue
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs

markdown_extensions:
  - admonition

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EnAccess
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/enaccessfdn

# Page tree
nav:
  # - Home: index.md
  - Firmware Documentation: firmware/index.md
  - Hardware Documentation: hardware/index.md
  - Web Software and API documentation: backend/index.md
