/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // gettingStartedSidebar: [{ type: 'autogenerated', dirName: 'getting-started' }],
  // backendSidebar: [{ type: 'autogenerated', dirName: 'backend' }],
  // firmwareSidebar: [{ type: 'autogenerated', dirName: 'firmware' }],
  // hardwareSidebar: [{ type: 'autogenerated', dirName: 'hardware' }],

  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'example',
  //   'example',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
};

export default sidebars;
