name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    name: Lint clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format lint
        working-directory: firmware
        run: find include/ src/ \( -name '*.[ch]pp' -o -name '*.h' \) | xargs clang-format --verbose --style=file -n --Werror

  compile-firmware-platform-io:
    name: Compile Firmware with PlatformIO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PlatformIO
        run: pipx install platformio
      - name: Compile the firmware
        working-directory: firmware
        env:
          PLATFORMIO_BUILD_FLAGS: -Werror
        run: pio run

  compile-firmware-selftest-platform-io:
    name: Compile Firmware for Self Test with PlatformIO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PlatformIO
        run: pipx install platformio
      - name: Compile the firmware for Self Test
        working-directory: firmware_selftest
        env:
          PLATFORMIO_BUILD_FLAGS: -Werror
        run: pio run
