name: OpenSmartMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    name: Lint clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format lint
        working-directory: firmware
        run: find include/ src/ \( -name '*.[ch]pp' -o -name '*.h' \) | xargs clang-format --verbose --style=file -n --Werror

  editorconfig-checker:
    name: Lint EditorConfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install "editorconfig-checker"
      - name: Run editorconfig-checker
        run: ec -exclude "hardware/"

  check-links:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check URLs in Markdown files
        run: |
          ERROR_FOUND=false

          find . -type f -name "*.md" -exec grep -hEo "(http|https)://[a-zA-Z0-9./?=_%:-]*" {} \; | sort -u | while read -r URL
          do
            STATUS=$(curl -s -o /dev/null -I -w "%{http_code}" "$URL")
            if [ "$STATUS" -eq 404 ]; then
              echo "::error title=HTTP $STATUS::$URL returned $STATUS"
              ERROR_FOUND=true
            fi
          done

          if [ "$ERROR_FOUND" = true ]; then
            exit 1
          fi

  compile-firmware-platform-io:
    name: Compile Firmware with PlatformIO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PlatformIO
        run: pipx install platformio
      - name: Compile the firmware
        working-directory: firmware
        env:
          PLATFORMIO_BUILD_FLAGS: -Werror
        run: pio run
