name: OpenSmartMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    name: Lint clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format lint
        working-directory: Firmware code/smart_energy_meter
        run: clang-format --style=file -n --Werror smart_energy_meter.ino
  compile-firmware:
    name: Compile Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install board and platform
        working-directory: Firmware code/smart_energy_meter
        run: |
          make install
      - name: Compile the firmware
        working-directory: Firmware code/smart_energy_meter
        run: |
          make compile
